/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a company and its owner, and signs the owner in. */
        post: operations["post_app_access_ui_http_auth_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is signed in. */
        get: operations["get_app_access_ui_http_auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posting-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every concept with the account it posts to, in the order of §5. */
        get: operations["get_app_ledger_ui_http_booksettings_postingrules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posting-rules/{concept}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Points a concept at another account: {account_id}. The account must be postable (409 account_not_postable) and
         *     within the concept's part of the PUC (422 account_not_allowed_for_concept). 404 for an unknown concept or
         *     another company's account.
         */
        put: operations["put_app_ledger_ui_http_booksettings_changepostingrule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/lock-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The fecha de bloqueo contable: nothing is emitted or voided on or before it. */
        get: operations["get_app_ledger_ui_http_booksettings_lockdate"];
        /** Moves the fecha de bloqueo: {locked_until: YYYY-MM-DD}, today at the latest (422 lock_date_in_future). */
        put: operations["put_app_ledger_ui_http_booksettings_movelockdate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The company's taxes. ?class=charge|withholding; ?all=1 includes the inactive ones. */
        get: operations["get_app_ledger_ui_http_catalog_taxes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The company's payment methods. ?all=1 includes the inactive ones. */
        get: operations["get_app_ledger_ui_http_catalog_paymentmethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Postable accounts for a picker: ?q= matches a code prefix or part of the name; ?purchases=1 only those usable on
         *     purchase lines. At most 20.
         */
        get: operations["get_app_ledger_ui_http_catalog_searchaccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The chart in code order: ?q= (digits: a code prefix; words: part of the name), ?class=1…9, ?page, ?per_page ≤ 100
         *     (default 50).
         */
        get: operations["get_app_ledger_ui_http_chart_list"];
        put?: never;
        /**
         * Adds a sub-account or auxiliar: {parent_code, code (the parent's plus two digits), name, usable_on_purchases?}.
         * @description 409 account_code_taken; 422 account_code_invalid, parent_account_not_found; 403 for the billing user.
         */
        post: operations["post_app_ledger_ui_http_chart_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * {name, active, usable_on_purchases}. A PUC account keeps its name (409 account_standard); an account a posting
         *     rule uses stays active (409 account_in_posting_rule); another company's id is 404.
         */
        put: operations["put_app_ledger_ui_http_chart_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entries by date and number, each with all its lines: ?from, ?to, ?account (a code: that account and its
         *     children), ?tercero_id, ?page, ?per_page ≤ 100 (default 25).
         */
        get: operations["get_app_ledger_ui_http_ledgerreport_journal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/trial-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per account and its parents: saldo anterior, débitos, créditos and nuevo saldo for ?from–?to. */
        get: operations["get_app_ledger_ui_http_ledgerreport_trialbalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/income-statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingresos, costos and gastos of ?from–?to, and the period's result. */
        get: operations["get_app_ledger_ui_http_ledgerreport_incomestatement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/balance-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activo, pasivo and patrimonio at ?date (default today). */
        get: operations["get_app_ledger_ui_http_ledgerreport_balancesheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terceros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search: ?q= (part of the name or identification, at least 3 characters on documents), ?role=cliente|proveedor|
         *     empleado|otro, ?active=1, ?page, ?per_page ≤ 100.
         */
        get: operations["get_app_party_ui_http_tercero_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terceros/quick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quick-create from inside a document (§4.2): {person_type, identification_type, identification_number,
         *     check_digit?, first_names?, last_names?, business_name?, email?, roles: [cliente|proveedor|…]} → 201.
         */
        post: operations["post_app_party_ui_http_tercero_quickcreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terceros/{id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A tercero's contacts, for the document header's Contacto. */
        get: operations["get_app_party_ui_http_tercero_contacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search: ?q= (part of the code or name), ?type=producto|servicio, ?active=1, ?page, ?per_page ≤ 100. */
        get: operations["get_app_catalog_ui_http_product_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/quick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quick-create from a document line (§4.3): {type, code, name, sale_price, price_includes_tax, charge_tax_id?,
         *     withholding_tax_id?} → 201.
         */
        post: operations["post_app_catalog_ui_http_product_quickcreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}/taxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Writes "use these taxes on this product from now on" (§4.6 line tax dialog): {charge_tax_id, withholding_tax_id}. */
        put: operations["put_app_catalog_ui_http_product_settaxes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionOutput: {
            user_id: string;
            email: string;
            name: string;
            /** owner, billing or accountant */
            role: string;
            company_id: string;
            company_name: string;
            company_nit: string;
            company_check_digit?: string | null;
        };
        PostingRuleOutput: {
            /** ingreso, descuento_ventas, iva_generado… (PostingConcept) */
            concept: string;
            account_id: string;
            account_code: string;
            account_name: string;
            allowed_prefixes: string[];
        };
        LockDateOutput: {
            /** YYYY-MM-DD, or null while the books are open. */
            locked_until?: string | null;
        };
        TaxOutput: {
            id: string;
            name: string;
            /** charge (impuesto cargo) or withholding (retención) */
            tax_class: string;
            /** none, iva, impoconsumo, retefuente, reteiva, reteica */
            kind: string;
            /** percentage or per_unit */
            calculation: string;
            /** Decimal string: a percentage ("19.0000") or a value per unit ("500.0000"). */
            rate: string;
            sales_account_id?: string | null;
            purchase_account_id?: string | null;
            valid_from?: string | null;
            valid_to?: string | null;
            active: boolean;
            standard: boolean;
        };
        PaymentMethodOutput: {
            id: string;
            name: string;
            /** cash (contado) or credit (crédito) */
            kind: string;
            account_id?: string | null;
            account_code?: string | null;
            account_name?: string | null;
            active: boolean;
            standard: boolean;
        };
        AccountOutput: {
            id: string;
            code: string;
            name: string;
            /** debit or credit */
            nature: string;
            /** class, group, account, subaccount, auxiliary */
            level: string;
            parent_code?: string | null;
            standard: boolean;
            active: boolean;
            postable: boolean;
            usable_on_purchases: boolean;
        };
        JournalLineOutput: {
            account_id: string;
            account_code: string;
            account_name: string;
            tercero_id?: string | null;
            tercero_name?: string | null;
            /** Decimal string; one of débito and crédito is "0.00". */
            debit: string;
            credit: string;
            description?: string | null;
        };
        JournalEntryOutput: {
            id: string;
            number: number;
            date: string;
            /** sales_invoice, cash_receipt, purchase_invoice, supplier_payment… */
            source_type: string;
            source_id: string;
            source_number: string;
            description: string;
            /** The entry this one reverses (a void), if any. */
            reverses_id?: string | null;
            total_debit: string;
            total_credit: string;
            lines: components["schemas"]["JournalLineOutput"][];
        };
        TrialBalanceRowOutput: {
            code: string;
            name: string;
            /** class, group, account, subaccount, auxiliary */
            level: string;
            /** debit or credit */
            nature: string;
            /** Saldo anterior, débito minus crédito (a crédito balance is negative). */
            opening: string;
            debit: string;
            credit: string;
            /** Nuevo saldo, débito minus crédito. */
            closing: string;
        };
        TrialBalanceOutput: {
            from?: string | null;
            to: string;
            rows: components["schemas"]["TrialBalanceRowOutput"][];
            /** Σ débitos of the period. */
            total_debit: string;
            total_credit: string;
            /** Σ débitos = Σ créditos. */
            balanced: boolean;
        };
        StatementLineOutput: {
            code: string;
            name: string;
            /** group or account */
            level: string;
            amount: string;
        };
        StatementSectionOutput: {
            /** The PUC class: 1 activo, 2 pasivo, 3 patrimonio, 4 ingresos, 5 gastos, 6 costos de ventas, 7 costos de producción. */
            code: string;
            name: string;
            total: string;
            lines: components["schemas"]["StatementLineOutput"][];
        };
        IncomeStatementOutput: {
            from: string;
            to: string;
            sections: components["schemas"]["StatementSectionOutput"][];
            revenue: string;
            costs: string;
            expenses: string;
            gross_profit: string;
            net_income: string;
        };
        BalanceSheetOutput: {
            date: string;
            sections: components["schemas"]["StatementSectionOutput"][];
            /** The result of classes 4 to 7 not yet closed into patrimonio. */
            current_earnings: string;
            total_assets: string;
            total_liabilities: string;
            /** Class 3 plus the current earnings. */
            total_equity: string;
            /** Activo = pasivo + patrimonio. */
            balanced: boolean;
        };
        TerceroSummaryOutput: {
            id: string;
            display_name: string;
            /** persona or empresa */
            person_type: string;
            /** cc, nit, ce, pasaporte, … */
            identification_type: string;
            identification_number: string;
            check_digit?: string | null;
            email?: string | null;
            city?: string | null;
            roles: string[];
            active: boolean;
        };
        ContactOutput: {
            id: string;
            name: string;
            email?: string | null;
            phone?: string | null;
        };
        ProductOutput: {
            id: string;
            /** producto or servicio */
            type: string;
            code: string;
            name: string;
            description?: string | null;
            category_id?: string | null;
            category_name?: string | null;
            /** DIAN unit code (94 unidad…) */
            unit_code: string;
            /** Decimal string, four decimals: the list price. */
            sale_price: string;
            price_includes_tax: boolean;
            /** The line's unit value: the sale price, net of the charge tax when it includes it (§4.3). */
            unit_price_net_of_tax: string;
            charge_tax_id?: string | null;
            withholding_tax_id?: string | null;
            revenue_account_id?: string | null;
            expense_account_id?: string | null;
            active: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_app_access_ui_http_auth_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOutput"];
                };
            };
        };
    };
    get_app_access_ui_http_auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOutput"];
                };
            };
        };
    };
    get_app_ledger_ui_http_booksettings_postingrules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PostingRuleOutput"][];
                    };
                };
            };
        };
    };
    put_app_ledger_ui_http_booksettings_changepostingrule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                concept: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostingRuleOutput"];
                };
            };
        };
    };
    get_app_ledger_ui_http_booksettings_lockdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockDateOutput"];
                };
            };
        };
    };
    put_app_ledger_ui_http_booksettings_movelockdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockDateOutput"];
                };
            };
        };
    };
    get_app_ledger_ui_http_catalog_taxes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TaxOutput"][];
                    };
                };
            };
        };
    };
    get_app_ledger_ui_http_catalog_paymentmethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PaymentMethodOutput"][];
                    };
                };
            };
        };
    };
    get_app_ledger_ui_http_catalog_searchaccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AccountOutput"][];
                    };
                };
            };
        };
    };
    get_app_ledger_ui_http_chart_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AccountOutput"][];
                        total: number;
                        page: number;
                        per_page: number;
                    };
                };
            };
        };
    };
    post_app_ledger_ui_http_chart_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOutput"];
                };
            };
        };
    };
    put_app_ledger_ui_http_chart_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOutput"];
                };
            };
        };
    };
    get_app_ledger_ui_http_ledgerreport_journal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["JournalEntryOutput"][];
                        total: number;
                        page: number;
                        per_page: number;
                    };
                };
            };
        };
    };
    get_app_ledger_ui_http_ledgerreport_trialbalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrialBalanceOutput"];
                };
            };
        };
    };
    get_app_ledger_ui_http_ledgerreport_incomestatement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeStatementOutput"];
                };
            };
        };
    };
    get_app_ledger_ui_http_ledgerreport_balancesheet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceSheetOutput"];
                };
            };
        };
    };
    get_app_party_ui_http_tercero_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TerceroSummaryOutput"][];
                        total: number;
                        page: number;
                        per_page: number;
                    };
                };
            };
        };
    };
    post_app_party_ui_http_tercero_quickcreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerceroSummaryOutput"];
                };
            };
        };
    };
    get_app_party_ui_http_tercero_contacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ContactOutput"][];
                    };
                };
            };
        };
    };
    get_app_catalog_ui_http_product_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ProductOutput"][];
                        total: number;
                        page: number;
                        per_page: number;
                    };
                };
            };
        };
    };
    post_app_catalog_ui_http_product_quickcreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
        };
    };
    put_app_catalog_ui_http_product_settaxes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
        };
    };
}
